### ISSUE TITLE
Cities

### ISSUE THREAD

**Issue by contra** [jbielick/boundaries.io#3]
Any way to grab this data currently?

**Comment by jbielick** [comment]
The source of most of this data, [TIGER/Line®](https://www.census.gov/geo/maps-data/data/tiger-line.html) from the U.S. Census Bureau includes a `places` collection (which you will find in the boundaries.io API). These are incorporated places (most often cities [more info](https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2015/TGRSHP2015_TechDoc_Ch2.pdf).

Does that answer your question?

**Comment by jbielick** [comment]
For example:

`curl -H 'Accept: application/json' http://boundaries.io/geographies/places/named/New%20York`

```
{"_id":"55b3d2956404f4b780a44e6f","type":"Feature","properties":{"PCINECTA":"N","PLACENS":"02395220","LSAD":"25","FUNCSTAT":"A","ALAND":780864330,"INTPTLON":"-073.9385892","INTPTLAT":"+40.6636189","GEOID":"3651000","PCICBSA":"Y","STATEFP":"36","NAME":"New York","PLACEFP":"51000","NAMELSAD":"New York city"...
```

**Comment by contra** [comment]
@jbielick How do you tell in the response what's a city and what isn't?

I see in the TIGER data there is also "Urban Areas" "Metropolitan/Micropolitan Statistical Area" and "Condensed Cities" that might be useful for this

**Comment by jbielick** [comment]
Incorporated places is what you're looking for; city is a general term. There is no "city" attribute because that's not an attribute the census bureau records in these shapefiles.

Please feel free to browse and explore the TIGER/Line shapefiles if you think there's city boundary data contained in some of them ftp://ftp2.census.gov/geo/tiger/TIGER2015/ .

Consolidated Cities (CONCITY) is " unit of local government for which the functions of an incorporated place and its county or minor civil division (MCD) have merged." Urban Areas are not cities. Metropolitan Areas are also not cities. Download the shapefiles and convert to geojson or load in a GIS viewer if you think those might contain cities.

**Comment by jbielick** [comment]
A detailed explanation of each shapefile concept in TIGER/Lines can be found here: https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2015/TGRSHP2015_TechDoc_Ch3.pdf

**Comment by contra** [comment]
Great, so the places endpoint should handle this just fine. Wasn't clear what exactly "places" meant in the docs - thanks for the help!
